[metadata]
name = "config"
description = "A channel to select from your user's config files"
requirements = ["fd", "bat"]

[source]
command = "fd -t f . $HOME/.config"


[preview]
command = "bat -n --color=always '{}'"
