-- <------------ Copilot
--
return {
  "github/copilot.vim",
  lazy = false,
}
--
--
-- <------------ Supermaven
-- return {
--   "supermaven-inc/supermaven-nvim",
--   lazy = false,
--   config = function()
--     require("supermaven-nvim").setup {
--       keymaps = {
--         accept_suggestion = "<C-]>",
--         clear_suggestion = "<C-[>",
--       },
--       -- your configuration comes here
--       -- or leave it empty to use the default settings
--       -- refer to the configuration section below
--     }
--   end,
-- }
--
--
-- <------------ Codeium
--
-- Path: codeium.lua does not work at the moment
-- return {
--     "Exafunction/codeium.nvim",
--     -- lazy=false,
--     dependencies = {
--         "nvim-lua/plenary.nvim",
--         "hrsh7th/nvim-cmp",
--     },
--     config = function()
--         require("codeium").setup({
--         })
--     end
-- }
-- <------------ Sourcegraph
-- return {
--
--   "sourcegraph/sg.nvim",
--   lazy = false,
--   dependencies = { "nvim-lua/plenary.nvim" },
-- }
